targetInstance: ${TEST_URL:http://localhost:8095}

s2s-url: ${S2S_URL_FOR_TESTS:http://rpe-service-auth-provider-aat.service.core-compute-aat.internal}

s2s-name: rd_professional_api

idam.api.url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
oauth2.client.secret: ${CA_REF_OAUTH2_CLIENT_SECRET:b8b4c525-7fc4-4c14-84ef-54260c85277a}
idam.auth.clientId: ${CA_REF_OAUTH2_CLIENT_ID:rd-caseworker-ref-api}
idam.auth.redirectUrl: ${OAUTH2_REDIRECT_URI:https://rd-caseworker-ref-api-aat.service.core-compute-aat.internal/oauth2redirect}
s2s-secret: ${S2S_SECRET:Y2ROIZ3PW4WRHVQZ}
userProfUrl: https://rd-user-profile-api-pr-575.service.core-compute-preview.internal


